name: python formatter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-$-{{ hashFiles('requirements.txt')}}

    - name: install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install autopep8
        pip install --upgrade autopep8

    - name: running autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive *.py
